import localFont from 'next/font/local'
import './globals.css' 
// Font files can be colocated inside of `app`
const myFont = localFont({
  src: './BreatheFireIii-PKLOB.ttf',
  display: 'swap',
})
 
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={myFont.className}>
      <body>{children}</body>
    </html>
  )
}


export const metadata = {
  title: 'DND API',
  description: 'Generated by create next app',
}

